{
    "name": "Enhancement In Payment Mechanism",
    "summary": "",
    "version": "1.0",
    "license": "",
    "author": "Gerry's App",
    "category": "",
    "website": "http://www.gerrys.net",
    "depends": [
        "account",
        "hr_payroll",
        "sale",
        "purchase",
        "account_check_printing",
    ],
    "data": [
        "wizard/invoice_batch_process_view.xml",
        'wizard/sale_advance_payment_wiz.xml',
        'wizard/purchase_advance_payment_wiz.xml',
        'views/invoice_deductions_lines_view.xml',
        # 'views/delete_act_window.xml',
        'views/sale_order.xml',
        'views/purchase_order.xml',
        "views/invoice_view.xml",
        "views/account_tax_view.xml",
        "views/res_partner_view.xml",
        "views/account_payment_view.xml",
        "views/payment_deductions_view.xml",
        "wizard/multiple_writeoff_view.xml",
        "views/report_menu.xml",
        "views/deduction_report.xml",
        "views/payment_voucher_report.xml",
        "views/report_header.xml",
        "views/hr_payroll.xml",
        "security/ir.model.access.csv"
    ],
    "installable": True,
}
